services:
  bot:
    image: vbenny42/kanye_weast
    container_name: bot    
    volumes:
      - ~/.aws:/root/.aws
      - ./banned_users.pkl:/app/banned_users.pkl
      - ./database.db:/app/database.db
      - ./secrets.json:/app/secrets.json
