name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: |
        echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kanyeweastimage:$(date +%s)
      
    - name: Docker Push
      run: docker tag kanyeweastimage:$(date +%s) ${{secrets.DOCKER_USER}}/kanye_weast && docker push ${{secrets.DOCKER_USER}}/kanye_weast && docker logout
